# -*- coding: utf-8 -*-
"""Ecommerce customer behavior data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gp6S6zdGffXdYhyr9kRXb69LBoh9Jvly
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Machine Learning/ecommerce customer behavior.csv")

df.head()

df.tail()

print(df.describe())

print(df.info())

"""# Data Cleaning"""

df.duplicated().sum()

df.shape

# remove $
df["Purchase_Amount"] = df["Purchase_Amount"].replace('[$,]', '', regex=True).astype(float)

# convert date m-d-y to d-m-y
df["Time_of_Purchase"] = pd.to_datetime(df["Time_of_Purchase"])
df["Time_of_Purchase"] = df["Time_of_Purchase"].dt.strftime("%d-%m-%Y")

df.head()

# check missing
print(df.isnull().sum())

# missing value fill with none
df["Social_Media_Influence"] = df["Social_Media_Influence"].fillna("None")
df["Engagement_with_Ads"] = df["Engagement_with_Ads"].fillna("None")

df.isnull().sum()

df.info()

# gender wise total customer
df.groupby('Gender')['Customer_ID'].count()

def clean_gender(g):
    if g.lower () == 'male':
        return 'Male'
    elif g.lower() == 'female':
        return 'Female'
    else:
        return 'Others'

df['Gender1'] = df['Gender'].apply(clean_gender)

df['Gender1'].count()

# device used for the shopping
df["Device_Used_for_Shopping"].value_counts()

# total sales by Gender
df.groupby("Gender1")["Purchase_Amount"].sum()

# category wise purchase order count
df["Purchase_Category"].value_counts()

# Gender wise total total sales
plt.figure(figsize=(5,4))
payment_counts = df['Gender1'].value_counts()

payment_counts.plot.pie(autopct='%1.1f%%')
plt.title('Gender wise total Sales')
plt.ylabel('sum of sales')
plt.show()

# create a bar chart of marital status
plt.figure(figsize=(8,4))
sns.countplot(x="Marital_Status", data=df, width= 0.8, color = "purple")
plt.title("total Cusotmer marital status")
plt.show()

# age distribution chart
sns.histplot(df["Age"], bins=20, color= 'purple')
plt.title("Age Distribution")
plt.show()

# purchase category
plt.figure(figsize=(10,5))
sns.countplot(y="Purchase_Category", data=df, color= 'purple')
plt.show()

# payment method
sns.countplot(x="Payment_Method", data=df, color= 'purple')
plt.xticks(rotation=45)
plt.show()

# correlation between columns
plt.figure(figsize=(10,4))
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()

df.to_csv("Ecommers_Customer_Behavior_clean_data.csv", index=False)

#from google.colab import files
files.download("Ecommers_Customer_Behavior_clean_data.csv")